RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
		
Solution:

Set num_workers in DataLoader to 0

=======================================================================

object.__new__() takes exactly one argument (the type to instantiate)

Solution:

mispelled __init__() as init() (without underscores)

========================================================================